name: 编译发布

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: '预发布'
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false

  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取最新代码
        uses: actions/checkout@v4

      - name: 设置.NET环境
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: 更新软件包依赖
        run: dotnet restore

      - name: 编译
        id: build
        run: dotnet build --no-restore

      - name: 发布
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          prerelease: ${{ github.event.inputs.prerelease }}
          make_latest: true
          files: |
            metaST/bin/Debug/net8.0/*
