name: 编译发布

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag'
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取最新代码
        uses: actions/checkout@v4

      - name: 设置.NET环境
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: 更新软件包依赖
        run: dotnet restore

      - name: 编译并发布
        id: build
        run: |
          dotnet publish -c Release -r win-x64
          dotnet publish -c Release -r win-arm64
          dotnet publish -c Release -r linux-x64
          dotnet publish -c Release -r linux-arm64
          dotnet publish -c Release -r osx-x64
          dotnet publish -c Release -r osx-arm64

      - name: 文件移动、重命名
        id: rename
        run: |
          mkdir -p metaST/dest
          mv metaST/bin/Release/win-x64/publish/metaST.exe   metaST/dest/metaST-win-amd64.exe
          mv metaST/bin/Release/win-arm64/publish/metaST.exe metaST/dest/metaST-win-arm64.exe
          mv metaST/bin/Release/linux-x64/publish/metaST     metaST/dest/metaST-linux-amd64
          mv metaST/bin/Release/linux-arm64/publish/metaST   metaST/dest/metaST-linux-arm64
          mv metaST/bin/Release/osx-x64/publish/metaST       metaST/dest/metaST-mac-amd64
          mv metaST/bin/Release/osx-arm64/publish/metaST     metaST/dest/metaST-mac-arm64

      - name: 发布
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          body_path: ${{ github.workspace }}/CHANGELOG.md
          prerelease: false
          make_latest: true
          files: |
            metaST/dest/*
